### ISSUE TITLE
cant click anything in the customprofile options

### ISSUE THREAD

**Issue by qwwwwerty** [iArtie/CustomProfiles#1]
the geode options for the mod does nothing too

**Comment by iArtie** [comment]
If you're on Windows it won't do anything, you should go to the settings wheel that is in the profile, there you will find the customization, the geode settings are only for Android

**Comment by RoootTheFox** [comment]
on windows; the mentioned settings on the profile aren't clickable at all (as in, you can not interact with anything in the entire popup)

**Comment by iArtie** [comment]
I would like you to send me more information to try and fix that, my discord is "bitzgd"

**Comment by iArtie** [comment]
fixed! update the mod

**Comment by RoootTheFox** [comment]
since this is fixed now, you should maybe close the issue (it'll remain pinned for people to see)
