### ISSUE TITLE
Mod causes game to crash when trying to block someone's profile

### ISSUE THREAD

**Issue by Andromeda110K** [iArtie/CustomProfiles#3]
**The only steps to reproduce this error is using the mod and blocking anyone in the game, it just crashes.
This is the full crashlog:**

2024-04-26T15:45:29-0600
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "bitz.customprofiles" mod. Please submit this crash report to its developers (BitZ) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.25
Loader Commit: 20dc3c9
Bindings Commit: 2eb85b0
Installed mods: 32
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\bitz.customprofiles\bitz.customprofiles.dll
Faulty Mod: bitz.customprofiles
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 5E9D7A79 (bitz.customprofiles.dll + 7a79)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\bitz.customprofiles\bitz.customprofiles.dll + 7a79
 - 04F00657
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\weebify.separate_dual_icons\weebify.separate_dual_icons.dll + 1beab
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\weebify.separate_dual_icons\weebify.separate_dual_icons.dll + 1be6d
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\cvolton.betterinfo\cvolton.betterinfo.dll + 42534 (CreatorInfoPopup::CreatorInfoPopup + 6500)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\cvolton.betterinfo\cvolton.betterinfo.dll + 4212d (CreatorInfoPopup::CreatorInfoPopup + 5469)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\rynat.better_unlock_info\rynat.better_unlock_info.dll + 157ab
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\rynat.better_unlock_info\rynat.better_unlock_info.dll + 1576d
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\cvolton.misc_bugfixes\cvolton.misc_bugfixes.dll + 15ab5
 - 04F00657
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\itzkiba.better_progression\itzkiba.better_progression.dll + 5e47 (BP_ProfilePage::loadPageFromUserInfo + 87)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\itzkiba.better_progression\itzkiba.better_progression.dll + 5ded (geode::modifier::AsStaticFunction_loadPageFromUserInfo<BP_ProfilePage,void (__thiscall BP_ProfilePage::*)(GJUserScore *)>::Impl<void (__thiscall BP_ProfilePage::*)(GJUserScore *)>::function + 13)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 10cd96
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + f4429
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + f3e4f
 - 09611C9E
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\cvolton.betterinfo\cvolton.betterinfo.dll + 18513 (DailyViewLayer::DailyViewLayer + 42611)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\cvolton.betterinfo\cvolton.betterinfo.dll + 16431 (DailyViewLayer::DailyViewLayer + 34193)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 107031 (cocos2d::CCTimer::update + 97)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 106ec4 (cocos2d::CCScheduler::update + 276)
 - 04CE22B6
 - 099F1D49
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\mat.draw-divide\mat.draw-divide.dll + 141b
 - 099F196B
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 1759d4 (gdMainHook + 532 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:59)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 6be3b (RtlInitializeExceptionChain + 107)
 - C:\Windows\SYSTEM32\ntdll.dll + 6bdbf (RtlClearBits + 191)

== Register States ==
EAX: 00000001
EBX: 2225c958
ECX: 00fbeeec
EDX: 01390000
EBP: 00fbef04
ESP: 00fbee48
EDI: 00fbeec8
ESI: 00000000
EIP: 5e9d7a79

== Installed Mods ==
x | [v1.1.2] adyagd.godlikefaces
x | [v1.0.7] bitz.customprofiles
x | [v1.0.1] bitz.darkmode_v4
x | [v1.0.2] blueblock6.cleanstartpos
x | [v1.0.3] capeling.coloured-wave-trail
x | [v1.1.4] capeling.demons_in_garage_2.2
x | [v1.0.5] capeling.gamemode_picker
x | [v1.0.0] capeling.usable_explorers
x | [v4.1.9] cvolton.betterinfo
x | [v1.1.3] cvolton.misc_bugfixes
x | [v1.3.7] dankmeme.globed2
x | [v1.0.1] elsai.easing_preview
x | [v2.7.1] fleym.nongd
x | [v1.5.6] geode.custom-keybinds
x | [v2.0.0-beta.25] geode.loader
x | [v1.9.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.1.0] itzkiba.better_progression
x | [v1.1.0] itzkiba.grandpa_demon
x | [v1.0.1] mat.draw-divide
x | [v1.0.3] mat.run-info
x | [v1.1.1] ninkaz.blending_glow
x | [v2.2.2] prevter.openhack
x | [v1.2.0] raydeeux.hidepausebutton
x | [v1.0.3] relative.newgrounds_proxy
x | [v1.0.0] relative.scroll_faster_with_ctrl
x | [v1.1.0] rynat.better_unlock_info
x | [v1.6.9] thesillydoggo.entersearch
x | [v1.1.3] weebify.coins_in_pause_menu
x | [v1.1.2] weebify.restartbtn
x | [v1.0.3] weebify.separate_dual_icons
x | [v1.0.2] xiyxs.confirmpracticerestart

**Comment by iArtie** [comment]
Thanks, already fixed, I'm just fixing a couple more things to get the update out, probably in a few days

**Comment by iArtie** [comment]
Done! go to update CustomProfiles!
