### ISSUE TITLE
Config got reset every time the game closes

### ISSUE THREAD

**Issue by ndrew6075** [iArtie/CustomProfiles#4]
Every time I close and reopen the game, the last configuration was reset to the default

Before:
![image](https://github.com/user-attachments/assets/0db01e61-3d36-4687-817b-b147de3e7cf4)

After:
![image](https://github.com/user-attachments/assets/33ed4bfb-d302-43ce-baeb-6ab5696089d0)

Modifying settings.json did not help either, the file also got reset

**Comment by iArtie** [comment]
Ye, it's because the latest geode update (V3.5.0) did a complete rework of the settings, rather I'm surprised it's not broken, I'll fix it in these days, maybe tomorrow or the day after tomorrow

**Comment by iArtie** [comment]
fixed by geode team on geode V3.5.2
